### ISSUE TITLE
Добавить информацию из аккаунта Merch

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#1]
Tier, uploads и live брать из:
https://merch.amazon.com/accountSummary

**Comment by gilinykh** [comment]
```
{
  "eligibilityStatus": "ELIGIBLE",
  "publishedItemCount": "408",
  "isPublishingReady": true,
  "dailySubmissionCountRemaining": "100",
  "publishedItemCountLimit": "1000"
}
```

Похоже что так:
``publishedItemCountLimit`` - tier
``publishedItemCount`` - live
``dailySubmissionCountRemaining`` - максимальное значение uploads

**Comment by gilinykh** [comment]
Задал вопрос, точно будет известно завтра.

**Comment by fedotxxl** [comment]
done

**Comment by gilinykh** [comment]
> Tier:N/A Uploads:402 of 1000
> Tier should be 1000
> Uploads is a set amount based on tier. Maybe change this from uploads to Live

**Comment by fedotxxl** [comment]
done
