### ISSUE TITLE
Изменение шкалы графиков по максимальному отображаемому значению

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#10]
> on the dashboard - the vertical axis should probably adjust to how many there are - once you have more than 20 uploaded or updated (or sold I imagine) it gets hard to read the numbers

Если сделать просто, стоит сделать. Нужно отображать шкалу для графиков в зависимости от набора отображаемых значений. Сейчас она фиксирована и для больших значений (?) числа становятся нечитаемыми.

**Comment by fedotxxl** [comment]
done
