### ISSUE TITLE
Добавить отображение royalty в информацию о продажах

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#2]
В полях ``soldTotal``, ``soldTopMonth`` и ``soldToday``:

1. ``amount`` переименовывается в ``revenue``
2. добавляется поле ``royalty``, которое нужно отобразить

Также в ``soldTotal`` добавилось поле ``returns``, которое нужно учесть также как ``cancellations``
Добавить вертикальный скролл в *Products Sold Today* и *Top Products Sold This Month*

**Comment by gilinykh** [comment]
> Today's Sales:0$0
> Total Sales:534(563-29)$11928.51
> Total sales and Today's Sales should show both revenue and royalties

**Comment by fedotxxl** [comment]
done
