### ISSUE TITLE
Перераспределить карточки статистики на Дэшборде

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#22]
См. карточки в верхней части. Для карточек **This Month Royalties** и **Previous Month Royalties** API сейчас не предоставляет данных, так что показывать N/A

![image](https://user-images.githubusercontent.com/2765295/44771371-7a862300-ab73-11e8-9198-47324946da9f.png)

**Comment by fedotxxl** [comment]
api не предоставляет данных ни для одной из карточек

**Comment by fedotxxl** [comment]
done
