### ISSUE TITLE
Цвета продуктов не зафиксированы

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#23]
> Colors to match what we sent and stay consistent throughout – currently on one account popsockets are pink and on a different standard shirts are pink

Для разных аккаунтов должна быть одна и та же цветовая схема.

![image](https://user-images.githubusercontent.com/2765295/44771585-1021b280-ab74-11e8-88eb-4ca46777b2e0.png)

**Comment by fedotxxl** [comment]
Цвета продуктов зафиксированы согласно гамме и названиям продуктов. 
Названия продуктов в аккаунте не соответствуют указаынным на цветовой гамме

**Comment by gilinykh** [comment]
Цвета не соответствуют предложенной схеме

![chart-colors](https://user-images.githubusercontent.com/2765295/45207129-bf0a7080-b28f-11e8-978a-a3a8b2de42b9.png)

Кроме того, на недельном, месячном и годовом графиках используются разные цвета.

![chart-colors2](https://user-images.githubusercontent.com/2765295/45207178-f2e59600-b28f-11e8-8939-9f8de737279d.png)

**Comment by gilinykh** [comment]
Цвета поправил
