### ISSUE TITLE
Добавить элементу списка продуктов кнопку перехода на отчет

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#26]
Представление списка продуктов возвращает дополнительное поле ``productAnalysisReportUrl`` в виде (``http://132.148.25.147/MerchDatabaseReports/ReportViews?Path=/MerchDatabaseReports/Product Analysis&userId=%s``)
Добавить каждому продукту в списке кнопку перехода на этот отчет(**Analysis**), которая будет открывать ссылку в новой вкладке. В ссылку требуется дописывать в конце ``&asin=<ASIN>``

**Comment by gilinykh** [comment]
gilinykh/merch-api#2

**Comment by fedotxxl** [comment]
done
