### ISSUE TITLE
Изменения на списке продуктов

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#27]
1.Add show 10 products
~~2.Move img to next to brand, bullets and larger (height = height of the 3 lines and width is proportional)~~
3.The rows on the manage products grid - can they be alternating colors (Each ASIN alternate not each row within the ASIN) We were thinking light blue and white - just to provide some contrast between them
4.Add an all status to the filter and an all type to the product filter because people have trouble clicking the X to empty the filter once they have selected something

**Comment by gilinykh** [comment]
п. 2 убрали

**Comment by fedotxxl** [comment]
3. done
4. done
