### ISSUE TITLE
Настраиваемый период обновления

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#30]
> Can the product sync to be something configurable - either through a tomcat setting or in the database. At the moment - it seems like we want it to be every hour not every 24 - but until we see the load on the server - it is hard to tell.  The issue I am seeing is that the image link expires after an hour...trying to determine whether it is better to have a notice to remind people to sync products - or to allow more frequent syncs.

Фронт запрашивает данные о конфигурации синхронизации. Возвращается дата последней синхронизации и период. Фронт проверяет, что текущая дата не вышла за период. Если вышла - синхронизация.
(В АПИ конфигурируется период синхронизации и ведется дата последней синхронизации. При запросе они отдаются)

**Comment by fedotxxl** [comment]
done
