### ISSUE TITLE
Замена содержимого попапа при инвалидации сессии

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#31]
> The time out popup should be changed to read the following:
> Pop-up for Time-Out:
>
> Title  =  You have been logged out!
> 
> Description   =  Your Merch by Amazon account was automatically signed out due to Amazon policy. Please sign in now to refresh your data and continue your Merch By Amazon adventure!
>
>(Button) =  Click here to sign back into your account

**Comment by fedotxxl** [comment]
done
