### ISSUE TITLE
Кнопка удаления данных по продуктам и продажам

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#32]
>We need the delete option to show the below pop up (For deleted data) and also to delete sales at the same time as product data is removed.
>Pop-up for Deleted Data:
>
>Title = Your account data has been deleted from our servers!
>
>Description = You, or an administrator of your account, have opted delete all your Merch by Amazon data from your Merch Database Account.  Please note that your data will auto-sync if you log back into Merch Database after 12 hours.
>
>(Button) = Click here to log back into Merch Database and manually re-sync your account data!

По нажатию кнопки отправляется запрос на удаление данных по продуктам и продажам и показывается информационный попап.

**Comment by fedotxxl** [comment]
done

**Comment by gilinykh** [comment]
> change the text on delete popup to 
>
>"You have opted to delete all your Merch by Amazon data from your Merch Database Account. 
>Please note that your data will auto-sync if you log back into Merch Database after 12 hours. If you would like to view your data now, click Sync Products then Sync Sales"

**Comment by fedotxxl** [comment]
done
