### ISSUE TITLE
Дополнения по странице Dashboard

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#34]
>Add the Learn More url to all.
>The Learn More URL for Sales cards should go to http://132.148.25.147/MerchDatabaseReports/ReportViews?Path=/MerchDatabaseReports/Learn_More_Sales&userId=%s and the Learn More on Royalty cards should go to http://132.148.25.147/MerchDatabaseReports/ReportViews?Path=/MerchDatabaseReports/Learn_More_Royalty&userId=%s
>Change the icons on the cards as attached - shopping cart for sales and money for royalties. http://www.bootstrapdash.com/demo/stellar-admin-free/jquery/pages/icon 
>
>Switch the total sales and total royalties to the bottom left and move the This Month cards to the top right.
>Move Products Uploaded chart to left above Products sold today
>Move Products sold this month to the right
>reshow the updated chart on top of products sold this month - but change it to show returns and cancelled instead of updated
>Query - 
>select  ps.date,  p.shirt_type as type, sum(ps.cancellations) + sum(ps.returns) as value 
>from product_sale ps join product p on ps.asin = p.asin
> where p.user_id = ? group by ps.date, p.shirt_type order by ps.date desc

1.Добавить на карточки продаж и роялти ссылку *Learn More* 
2.Поменять иконку на карточках продаж на *shopping_cart* (https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-shopping-cart) и на карточке роялти на *money* (https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-money)
3.Переместить *total sales* и *total royalties* влево-вниз и переместить карточки *This Month* наверх-вправо
4.Переместить график загрузок налево над *Products Sold Today*
5.Переместить блок *Products Sold This Month* направо
6.Показать над блоком *Products Sold This Month* график возвратов и отмен

**Comment by fedotxxl** [comment]
done

**Comment by gilinykh** [comment]
> On the dashboard - it should read left to right Today's Sales, Today's Royalties, This Month Sales, This Month Royalties then the second line should be Total Sales, Total Royalties, Last Month Sales, Last Month Royalties. So basically flip the todays and total cards Remove learn more from Recent Product Sales Graph and Products Sold tables below

1.Поменять порядок total-карточек. Слева-направо должны идти:
- в первой линии Today's Sales, Today's Royalties, This Month Sales, This Month Royalties
- во второй линии Total Sales, Total Royalties, Last Month Sales, Last Month Royalties
2.Убрать ссылку Learn More с Recent Product Sales Graph и Products Sold
