### ISSUE TITLE
Синхронизация после разлогинивания должна выдавать предупреждение

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#4]
ШАГИ:
1. Логин в систему
2. Нажатие на кнопку синхронизации (УСПЕШНО)
3. Разлогинивание
4. Нажатие на кнопку синхронизации

ОЖИДАЕТСЯ:
Выдается предупреждение о невозможности выполнения синхронизации по причине отсутствия пользовательской аутентификации.

ПРОИСХОДИТ:
Никакой реакции, как будто все прошло успешно.

Можно использовать обращение к ``accountSummary`` (из #1 ) и по ответу понимать текущий статус аутентификации.

**Comment by fedotxxl** [comment]
done
