### ISSUE TITLE
Логаут при обновлении дэшборда

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#40]
**Шаги:**
Находясь на странице дэшборда обновить страницу (ctrl-f5).

**Ожидается:**
Страница обновилась

**Происходит:**
Появляется попап "You have been logged out!"

**Comment by gilinykh** [comment]
Для проверки действительности токена нужно использовать проверку [профиля ](https://developer.amazon.com/docs/login-with-amazon/obtain-customer-profile.html)Амазон. А именно:
```
https://api.amazon.com/user/profile?access_token=AtzaIIQEBLjAsAhRmHjNgHpi0UDme37rR6CuUpSR...
```

И проверять код 400 и error_code = invalid_token

**Comment by fedotxxl** [comment]
done

**Comment by gilinykh** [comment]
**Шаги:**
1. Выгрузить расширение
2. Залогаутиться из мерча
3. Почистить ресурсы приложения (Dev tools -> Applilcation). Куки, хранилища
4. Снова загрузить расширение, залогиниться в мерч и перейти в расширение

**Ожидается:**
Показывается дэшборд

**Происходит:**
Показывается попап "You have been logged out". При этом `background.html` не отображает никаких сделанных запросов.
