### ISSUE TITLE
Изменения на списке продуктов

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#5]
1. Число продуктов в Total By Product показывать отдельной колонкой для выравнивания
2. Добавить чекбокс выбирающий все продукты на странице
3. В колонке с типом продукта показывать тип полностью (можно делать перенос строки)
4. В колонке с названием показывать его полностью (можно делать перенос строки)
5. Отображать даты в формате MM/DD/YYYY
6. Добавить мультиселекты для установки фильтров по типу и статусу и передавать их в поиск (&status=LIVE&status=DRAFT&type=STANDARD_BRAND&type=PREMIUM_BRAND)
7. Добавить в каждую строку область, в которой показывать BRAND, TITLE, BULLET1, BULLET2 и DESCRIPTION
8. Заменить на иконки ссылки VIEW и EDIT
9. Убрать заголовок с колонки IMAGE
10. Увеличить размер изображения на 30%
11. Проценты не должны округляться 
> Total with 1 sale is not accurate (says 1). Percent with one sale should be the 136 ASINs that have sold divided by the 396 live.

**Comment by fedotxxl** [comment]
1+
2+
3+
4+
5+
6 ?
7 ?
8 +
9 + 
10 + 
11 ?

**Comment by fedotxxl** [comment]
done

**Comment by gilinykh** [comment]
> Edit Listing - Price needs to be listed and searchable
> Count of listings found by search added
> Dates all should be formatted wit the month first, then day, then year

5.Отображать даты в формате MM/DD/YYYY

12.Добавить сортируемую колонку с ценой
13.Показывать количество найденных записей по результату поиска

**Comment by fedotxxl** [comment]
done
