### ISSUE TITLE
Изменять ссылку на страницу редактирования для типа POP_SOCKET

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#7]
> Another small note - with the addition of pop-sockets (I have just been able to list them) the edit link is dependent on product type. If it is a shirt - it goes as normal - bit if shirt_type in the database is POP_SOCKET the edit link looks like : https://merch.amazon.com/merch-popsocket/title-setup/PH9M78XD1BT/add_details
>
> The difference is merch-popsocket vs merch-tshirt

Ссылка должна содержать ``merch-popsocket`` вместо ``merch-tshirt`` для типа POP_SOCKET

**Comment by fedotxxl** [comment]
done
