### ISSUE TITLE
Функция открытия в новых окнах вместо этого открывает в новых табах

### ISSUE THREAD

**Issue by gilinykh** [gilinykh/merch-ext#9]
> When I click Action On Selected Items (Open In New Windows) for 12 listings It opens one new window with 12 tabs - I was expecting 12 new windows

**ОЖИДАЕТСЯ:**
При выборе нескольких продуктов и выборе действия "Open In New Windows" эти продукты должны открываться в новых окнах. 

**ПРОИСХОДИТ:**
Сейчас выбранные продукты открываются в новых табах в этом же окне.

**Comment by fedotxxl** [comment]
done
